apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nginx-ex
  title: Nginx example service
  description: |
    This is a simple Nginx service
  links:
    - title: My Nginx Website
      url: https://myapp.example.com
  annotations:
    backstage.io/kubernetes-id: 'nginx-ex'
    backstage.io/kubernetes-namespace: myapps
    backstage.io/kubernetes-label-selector: 'app=nginx'
spec:
  type: service
  system: myapp
  owner: frontend-team
  lifecycle: production
